name: RUN AMSTERDAM SCRAPER

on:
  schedule:
    - cron: '0 15 * * 4'  # Run weekly on Thursday at 10:00 AM EST (15:00 UTC)
  workflow_dispatch:     # Allow manual triggering

jobs:
  scrape-and-combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # Run from this branch

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run data pipeline
        env:
          AUTH_COOKIE: ${{ secrets.AUTH_COOKIE }}
        run: python ./scrapers/run_pipeline.py
        
      - name: Commit and push if changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update league data: $(date)" && git push)
